before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inotify-tools
language: elixir
script:
  - mix meditate
matrix:
  include:
    - elixir: 1.5.1
      otp_release: 20.0
    - elixir: 1.6.5
      otp_release: 20.0
    - elixir: 1.7.3
      otp_release: 21.0